### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by vitalPleonasm** [loeweX/AmortizedCausalDiscovery#1]
I ran into an error when running the spring demo:
0) Running in Ubuntu 20.04, bash setup_dependencies.sh didn't run, so I simply followed the steps manually exactly as they appear in setup_dependencies.sh
1) sklearn dependency wasn't found in environment ACD, so I added it manually by installing anaconda into the environment.
2) python -m data.generate_dataset - this ran and populated the data directory, although I had to add --datadir <my datadir path> to override the default to your home directory.
3) python -m train --suffix _springs5 - this printed out some information, but then failed, with the message ending with
File "<my directory>/codebase/utils/data_loader.py", line 357 ..."temperatures" referenced before assignment.

If I'm reading the code properly, there is a combination of arguments that is skipping the assignment of temperature in data_loader, probably this:
args.load_temperatures = False
args.cuda = False

I tried to figure out where args.cuda is assigned, but I don't see it yet.  Is there a recommended set of python -m options for this situation?  My system has CUDA GPUs and I've used them in PyTorch before, but maybe the environment isn't working correctly?

**Comment by loeweX** [comment]
Hi,
Thanks for your interest in our codebase!

I've fixed two of the errors you've pointed out: 
1) I've added the dependency for sklearn to environment.yml, so now it should be installed automatically when creating a conda environment with that file.
2) I've fixed the error in File "/codebase/utils/data_loader.py", line 357, such that is is possible to have both args.load_temperatures and args.cuda set to false.

args.cuda is set [here](https://github.com/loeweX/AmortizedCausalDiscovery/blob/d1830abf4ae770a5a3582d31a5b584b74a21bad6/codebase/utils/arg_parser.py#L278) depending on a command-line parameter and whether cuda is available according to your pytorch installation. On my system, I manually had to install the cuda-enabled pytorch version to be able to use the GPU. This command might do the trick for you as well: `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
You can double-check [here](https://pytorch.org/) to get the right pytorch installation command.
