### ISSUE TITLE
Do you enforce that the predicted causal graphs are the same for all samples in the Netsim experiment?

### ISSUE THREAD

**Issue by chocolates** [loeweX/AmortizedCausalDiscovery#10]
Hi,

After reading your code, it seems that **the predicted causal graphs for different samples can be different even in the Netsim experiment**. The edge_accuracy is computed using the predicted causal graphs (which can be different for different samples) and the ground-truth causal graphs (which are the same for all samples). Could you please let me know if I am correct or not?

It would be great to hear from you.

**Comment by loeweX** [comment]
Hi,

Thanks for your interest in our codebase. It is indeed correct that the model may predict different causal graphs for each sample in the Netsim dataset, even though there is only a single underlying causal graph shared by all samples.

Best,
Sindy
