### ISSUE TITLE
kl_categorical_uniform returns negative value

### ISSUE THREAD

**Issue by charlio23** [loeweX/AmortizedCausalDiscovery#3]
https://github.com/loeweX/AmortizedCausalDiscovery/blob/91111204bc0b2763dbc100a85ffc1eea27e8317e/codebase/model/utils.py#L108

The `kl_categorical_uniform` method in `utils.py` returns a negative value. This does not seem like the expected result since in optimisation its absolute value increases. Moreover, the KL divergence should be always greater than 0 theoretically. Taking into account that the prior is uniform, shouldn't this modification be more appropriate?
` kl_div = preds * (torch.log(preds + eps) - np.log(1/num_edge_types)) `

**Comment by dmadras** [comment]
That modification is correct - however since it only changes the value by a constant it should not affect optimization. If you want to look at that value of KL you can use the add_const=True option in the kl_categorical_uniform method.

**Comment by charlio23** [comment]
Oh, I see. Then it's alright, thanks!
