### ISSUE TITLE
Graph visualization

### ISSUE THREAD

**Issue by manmeet3591** [loeweX/AmortizedCausalDiscovery#7]
I tried running the code with netsim data. I am unable to find the causal discovery graph which is estimated by ACD

**Comment by loeweX** [comment]
You can find the graph here:

https://github.com/loeweX/AmortizedCausalDiscovery/blob/4d1661118c9fcfbefbbd00226bc41f7a76743e11/codebase/utils/forward_pass_and_eval.py#L184

Essentially, the encoder outputs a connectivity matrix where each entry represents the probability of that particular edge existing.
