### ISSUE TITLE
question about the implementation

### ISSUE THREAD

**Issue by 7-qiliu** [loeweX/AmortizedCausalDiscovery#8]
Thank you for the great work. I have some questions on your implementation.

1. About causal graph
  - what is the difference between [edges and prob](https://github.com/loeweX/AmortizedCausalDiscovery/blob/master/codebase/utils/forward_pass_and_eval.py#L184) in forward_pass_and_eval.py
2. About loss function
  - what's the intuition behind the mechanism of [acc and auroc](https://github.com/loeweX/AmortizedCausalDiscovery/blob/master/codebase/utils/forward_pass_and_eval.py#L261) in forward_pass_and_eval.py. I can understand that we need to uncover the latent causal graph, however, here the interaction pattern is the dense graph, which would violate the sparse mechanism in causality. Would you mind giving some hints on this point?

Thanks again for making the code available.
Your response will be highly appreciated.

**Comment by loeweX** [comment]
Thanks for your interest in our work!

Regarding question 1), `edges` represent discrete samples, i.e. a binary choice whether or not a certain edge in the graph exists. `prob` on the other hand, represents the probability of the edge existing and is therefore a continuous value in the range [0,1].

Regarding question 2), we never actually use the accuracy or AUROC for the training of our model, but only to evaluate its causal discovery performance. And indeed, the summary graph that we predict with ACD is a dense graph that may contain cycles, however, we assume that the unrolled graph over time is a DAG.

Hope this helps!
